<?php

namespace AppBundle\Repository;

/**
 * ResourceErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceErrorRepository extends \Doctrine\ORM\EntityRepository
{
}
