onion_index:
    path: /
    defaults: { _controller: AppBundle:Onion:index }

onion_show:
    path: /{hash}
    defaults: { _controller: AppBundle:Onion:show }

#onion_check:
#    path: /{hash}/check
#    defaults: { _controller: AppBundle:Onion:check }
