homepage:
    path: /
    defaults: { _controller: AppBundle:Default:homepage }

search:
    path: /search
    defaults: { _controller: AppBundle:Default:search }

onion:
    resource: "@AppBundle/Resources/config/routing/onion.yml"
    prefix: /onion

resource:
    resource: "@AppBundle/Resources/config/routing/resource.yml"
    prefix: /url

word:
    resource: "@AppBundle/Resources/config/routing/word.yml"
    prefix: /word
