AppBundle\Entity\Onion:
    type: entity
    table: onion
    repositoryClass: AppBundle\Repository\OnionRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        hash:
            type: string
            length: 56
        countReferedOnions:
            type: integer
        countRefererOnions:
            type: integer
        dateCreated:
            type: datetime
    manyToMany:
        referedOnions:
            targetEntity: Onion
            inversedBy: refererOnions
            joinTable:
                name: onion_onion
                joinColumns:
                    referer_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    refered_id:
                        referencedColumnName: id
            cascade: ["persist", "remove"]
        refererOnions:
            targetEntity: Onion
            mappedBy: referedOnions
            cascade: ["remove"]
    oneToMany:
        onionWords:
            targetEntity: OnionWord
            mappedBy: onion
            cascade: ["remove"]
        resources:
            targetEntity: Resource
            mappedBy: onion
            cascade: ["remove"]
    oneToOne:
        resource:
            targetEntity: Resource
            joinColumn:
                name: resource_id
                referencedColumnName: id
                nullable: true
                cascade: ["persist"]
                onDelete: "SET NULL"
    uniqueConstraints:
        onion_hash_idx:
            columns: [ hash ]
