AppBundle\Entity\ResourceError:
    type: entity
    table: resource_error
    repositoryClass: AppBundle\Repository\ResourceErrorRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        label:
            type: string
            length: 191
        count:
            type: integer
        dateCreated:
            type: datetime
        dateLastSeen:
            type: datetime
            nullable: true
    manyToOne:
        resource:
            targetEntity: Resource
            inversedBy: errors
    uniqueConstraints:
        resourcerror_label_resource_idx:
            columns: [ label, resource_id ]
