AppBundle\Entity\ResourceWord:
    type: entity
    table: resource_word
    repositoryClass: AppBundle\Repository\ResourceWordRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        count:
            type: integer
        dateCreated:
            type: datetime
        dateSeen:
            type: datetime
    manyToOne:
        resource:
            targetEntity: Resource
            inversedBy: resourceWords
            joinColumn:
                onDelete: "CASCADE"
        word:
            targetEntity: Word
            inversedBy: resourceWords
            joinColumn:
                onDelete: "CASCADE"
    uniqueConstraints:
        rword_resource_word_uniq_idx:
            columns: [ resource_id, word_id ]
    indexes:
        rword_count_idx:
            columns: [ count ]
