AppBundle\Entity\Resource:
    type: entity
    table: resource
    repositoryClass: AppBundle\Repository\ResourceRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        url:
            type: text
        hashUrl:
            type: string
            column: url_hash
            length: 191
        title:
            type: text
            nullable: true
        description:
            type: text
            nullable: true
        contentType:
            type: string
            length: 191
            nullable: true
        httpCode:
            type: string
            length: 3
            nullable: true
        domain:
            type: string
            length: 191
            nullable: true
        subdomain:
            type: text
            nullable: true
        lastLength:
            type: integer
            nullable: true
        relevance:
            type: integer
        totalSuccess:
            type: integer
            column: success_total
        countErrors:
            type: integer
            column: error_count
        lastError:
            type: string
            length: 191
            column: error_last
            nullable: true
        dateCreated:
            type: datetime
        dateChecked:
            type: datetime
            nullable: true
        dateFirstSeen:
            type: datetime
            nullable: true
        dateLastSeen:
            type: datetime
            nullable: true
        dateError:
            type: datetime
            nullable: true
    manyToMany:
        referedResources:
            targetEntity: Resource
            inversedBy: refererResources
            joinTable:
                name: resource_resource
                joinColumns:
                    referer_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    refered_id:
                        referencedColumnName: id
            cascade: ["persist"]
        refererResources:
            targetEntity: Resource
            mappedBy: referedResources
    manyToOne:
        onion:
            targetEntity: Onion
            inversedBy: resources
            joinColumn:
                name: onion_id
                referencedColumnName: id
            cascade: ["persist"]
    oneToMany:
        errors:
            targetEntity: ResourceError
            mappedBy: resource
            cascade: ["persist"]
        resourceWords:
            targetEntity: ResourceWord
            mappedBy: resource
    uniqueConstraints:
        url_hash_idx:
            columns: [ url_hash ]
