AppBundle\Entity\Resource:
    type: entity
    table: resource
    repositoryClass: AppBundle\Repository\ResourceRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        url:
            type: string
            length: 191
        hashUrl:
            type: string
            column: url_hash
            length: 191
        title:
            type: text
            nullable: true
        lastLength:
            type: integer
            nullable: true
        totalSuccess:
            type: integer
            column: success_total
        countErrors:
            type: integer
            column: error_count
        lastError:
            type: string
            length: 191
            column: error_last
            nullable: true
        dateCreated:
            type: datetime
        dateChecked:
            type: datetime
            nullable: true
        dateSeen:
            type: datetime
            nullable: true
        dateError:
            type: datetime
            nullable: true
    manyToOne:
        onion:
            targetEntity: Onion
            inversedBy: resources
            joinColumn:
                name: onion_id
                referencedColumnName: id
    uniqueConstraints:
        url_hash_idx:
            columns: [ url_hash ]
